default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: pass # デフォルトだと空欄になっているはずなので変更
  host: db # デフォルトだとlocalhostになっているはずなので変更

development:
  <<: *default
  database: myapp_enpit_development

test:
  <<: *default
  database: myapp_enpit_test

production:
  <<: *default
  adapter: postgresql
  encoding: utf8
  pool: 5
